# Results

```{r}
df <- read.csv('finaldf.csv',encoding = "UTF-8")
```

```{r}
library(ggplot2)
library(tidyverse)

ggplot(df, aes(x = fct_infreq(restaurant_main_type))) + 
  geom_histogram(stat = 'count', binwidth=1, fill='lightblue') +
  theme_bw() +
  theme(axis.text.x=element_text(angle=90,hjust=1)) +
  ggtitle("Number of each restaurant type") +
  labs(x = 'restaurant type')
  
```




```{r, fig.width=10}
ggplot(df, aes(x=average_review,y=violation_count, color = restaurant_main_type)) +
  geom_point() +
  ggtitle("Average review vs. Violation count")

```

```{r}
rest_type <- aggregate(df$violation_count, by= list(df$restaurant_main_type), FUN =mean)
#rest_type$count <- 
rest_count <- aggregate(df$restaurant_type, by= list(df$restaurant_main_type), FUN = length)
rest_type <- merge(rest_type, rest_count, by = 'Group.1',all = TRUE)

colors <- c('avg'='red','count'='blue')

rest_type = rest_type %>%
  mutate(Type = fct_reorder(Group.1, x.x)) 
  ggplot(rest_type,(aes(y=Type))) +
  geom_point(aes(x=x.x),color='red') +
  ggtitle('Average violation counts by type') +
  labs(x='average violation',y='restaurant type')
  #geom_point(aes(x=x.y,color='count')) +
  #labs(x=color = 'Legend') +
  #scale_color_manual(values = colors)



```

```{r}
library(ggmosaic) 
library(colorRamps)


ggplot(data = df) +
  geom_mosaic(aes(x=product(price_range),fill=restaurant_main_type)) +
  scale_fill_manual(values =  primary.colors(21)) +
  ggtitle('Price range of each restaurant type') +
  labs(x='price range',y='restaurant type') #+
  #scale_x_discrete(limits = c('<30','30-50','>50'),
                   #labels=c('$30 and under','$31 to $50','$50 and over'))
  

```

```{r}
library(dplyr)

Manhhattan_zips <- c(10026, 10027, 10030, 10037, 10039, 10001, 10011, 10018, 10019, 10020, 10036,	10029, 10035,10010, 10016, 10017, 10022,
                     10012, 10013, 10014,	10004, 10005, 10006, 10007, 10038, 10280,	10002, 10003, 10009, 10021, 10028, 10044, 10065, 10075, 10128,
                     10023, 10024, 10025, 10031, 10032, 10033, 10034, 10040)

df_man <- df[df$postal_code %in% Manhhattan_zips,] 

df_man <- df_man %>%
  mutate(Neighborhood = case_when(
    postal_code %in% c(	10026, 10027, 10030, 10037, 10039) ~ "Central Harlem",
    postal_code %in% c(10001, 10011, 10018, 10019, 10020, 10036) ~ 'Chelsea and Clinton',
    postal_code %in% c(10029, 10035) ~ 'East Harlem',
    postal_code %in% c(10010, 10016, 10017, 10022) ~ 'Gramercy Park and Murray Hill',
    postal_code %in% c(10012, 10013, 10014) ~ 'Greenwich Village and Soho',
    postal_code %in% c(10004, 10005, 10006, 10007, 10038, 10280) ~ 'Lower Manhattan',
    postal_code %in% c(10002, 10003, 10009) ~ 'Lower East Side ',
    postal_code %in% c(10021, 10028, 10044, 10065, 10075, 10128) ~ 'Upper East Side',
    postal_code %in% c(10023, 10024, 10025) ~ 'Upper West Side',
    postal_code %in% c(10031, 10032, 10033, 10034, 10040) ~ 'Inwood and Washington Heights'
  ))

avg_violation <- aggregate(df_man$violation_count, by = list(df_man$Neighborhood), FUN = mean)

ggplot(avg_violation,aes(reorder(Group.1,-x,sum),x))+
  geom_col(binwidth=1, fill='lightblue') +
  theme_bw() +
  theme(axis.text.x=element_text(angle=60,hjust=1)) +
  ggtitle("Average vioaltion count by neighborhood") +
  labs(x = 'Neighborhood',y = 'average violation count')

```

```{r,fig.height=6}
df_man %>%
  group_by(Neighborhood, restaurant_main_type) %>%
  summarize(count = n()) %>%
  ggplot(aes(fct_relevel(Neighborhood),count)) +
  geom_bar(aes(fill = restaurant_main_type), position = "stack", stat = "identity") +
  scale_fill_manual(values =  primary.colors(21)) +
  theme(axis.text.x=element_text(angle=60,hjust=1)) +
  ggtitle('Total vioaltion in each neighborhood by restaurant type') +
  labs(x='Neighborhood')
```

```{r}

```
